# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Starport < Formula
  desc "Friendly CLI tool for developing Cosmos SDK apps."
  homepage "https://github.com/tendermint/starport"
  version "0.19.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tendermint/starport/releases/download/v0.19.1/starport_0.19.1_darwin_amd64.tar.gz"
      sha256 "4c17af56996f02bfe93a4f834292eeb7628e1c9fde19e50fd6ee99f9246b9629"

      def install
        bin.install "starport"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tendermint/starport/releases/download/v0.19.1/starport_0.19.1_linux_amd64.tar.gz"
      sha256 "056a953ea7e9be2194ba32262df3eea90b96a47dea0d4ce2b75cd7b0c1180e67"

      def install
        bin.install "starport"
      end
    end
  end
end
