# This file was generated by GoReleaser. DO NOT EDIT.
class Starport < Formula
  desc "CLI tool for developing Cosmos SDK apps."
  homepage "https://github.com/tendermint/starport"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tendermint/starport/releases/download/v0.0.9/starport_0.0.9_darwin_amd64.tar.gz"
    sha256 "2eecbe527a492881d74fded93b4a84ba10297763effa317760fd88ab04c92d6d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tendermint/starport/releases/download/v0.0.9/starport_0.0.9_linux_amd64.tar.gz"
      sha256 "3e6a7136a94bdfea9b0c28fef37cf98cb0232698dac0acbd0ed0d3ceff9afc6d"
    end
  end

  def install
    bin.install "starport"
  end
end
