# This file was generated by GoReleaser. DO NOT EDIT.
class Starport < Formula
  desc "CLI tool for developing Cosmos SDK apps."
  homepage "https://github.com/tendermint/starport"
  version "0.0.10-rc.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/tendermint/starport/releases/download/v0.0.10-rc.1/starport_0.0.10-rc.1_darwin_amd64.tar.gz"
    sha256 "0e182de9df034666ce47d529816286cfd67ad7a90d23f6a48dd7920d4dfaf75a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/tendermint/starport/releases/download/v0.0.10-rc.1/starport_0.0.10-rc.1_linux_amd64.tar.gz"
      sha256 "e9257703c7cf5a926d5a4874bd9575b42304bf79e900e34a0a3c41ff7ad03ca5"
    end
  end

  def install
    bin.install "starport"
  end
end
